from asyncio import exceptions
import requests
import time


cookies = {
        '_ga': 'GA1.3.509434785.1645514520',
        '_gid': 'GA1.3.353909799.1648728872',
        'PHPSESSID': 'mmjhcfda4un4lm2sjoavvn0cq2',
        'locale': 'en-us',
        'timezone': '+0800',
        'noteFontSize': '100',
        'noteExpand': '0',
        }




headers = {
        'Connection': 'close',
        'Cache-Control': 'max-age=0',
        'Upgrade-Insecure-Requests': '1',
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.82 Safari/537.36',
        'Sec-Fetch-Dest': 'document',
        'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9',
        'Sec-Fetch-Site': 'none',
        'Sec-Fetch-Mode': 'navigate',
        'Sec-Fetch-User': '?1',
        'Sec-Fetch-Dest': 'document',
        'Accept-Encoding': 'gzip, deflate',
        'Accept-Language': 'en-US,en;q=0.9',
        'If-None-Match': 'W/"5e659e99-1542"',
        'If-Modified-Since': 'Mon, 09 Mar 2020 01:40:41 GMT',
        }


while(True):
        try:
                response = requests.get('https://ncueeclass.ncu.edu.tw/media/doc/67880', headers=headers, cookies=cookies)
                print("done")
        except requests.exceptions.ConnectionError:
                time.sleep(5)
                print("ConnectionError, then rebuild Connection")
                continue
                



